config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  root 'home#index'

  #get '/' => 'home#index'
  get '/about' => 'home#about'
  get '/contact' => 'home#contact'
  get '/blogs' => 'blogs#index'


  #post '/blog' => 'blogs#create'
  #patch '/blog' => 'blogs#update'

  #delete '/blog' => 'blogs#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	def index
		@blog = Blog.order(updated_at: :desc)
	end 

	def create

		username = params[:username]
		title = params[:title]
		body = params[:body]

		Blog.create title: title, body: body, username: username
		#render status: 200, json: @controller.to_json
		redirect_to blogs_path
		#redirect_to "/blogs"
	end

	def update
		id = params[:id]
		title = params[:title]
		body = params[:body]

		b = Blog.find(id)
		b.update(title: title, body: body)

		render status: 200, json: @controller.to_json
	end

	def destroy
		id = params[:id]
		Blog.find(id).destroy
		redirect_to blogs_path
 
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def blogs
  end

  def temp
  	redirect_to root_path
  end

  def test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blogs/index.html.erb
<div class="blog ">
	<div class="intro">
	<h2>Blog</h2>

		<div class="blogHeader">
			<button type="button" class="btn btn-primary rightAligned" data-toggle="modal" data-target="#new-blog-modal"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add a new Post</button>
		</div>
		<% @blog.each do |b| %>
			<div class="blogPost" id="<%= b.id %>">
				
	  			<h3><input type="text" name="title" class="form-control titleInput" id="" style="display:none;" value="<%= b.title %>" required><span class="titleSpan"><%= b.title %></span></h3>
	  			
	  			<div id="<%= b.id %>" class="blogButtons">
		  			<button type="button" class="btn btn-primary btn-sm editButton"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit</button>


					<%= link_to(blog_path(b), method: :delete, class: 'btn btn-danger btn-sm deleteButton') do %>
						<span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete
					<%- end %>
					
					<button type="button" class="btn btn-primary btn-sm postButton" style="display:none;"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Save</button>
				</div>
	  			<div class="panel panel-default">
	    			<div class=" panel-heading userName" ><span class="glyphicon glyphicon-user userName" aria-hidden="true"></span> <%= b.username %></div>
	    			<div class="panel-body bodyText transparent"><textarea class="form-control bodyInput" id="" required style="display:none;"><%= b.body %></textarea><span class="bodySpan"><%= b.body %></span></div>
	  			</div>
			</div>

		<% end %>
	</div>
		<%= render 'home/new_blog_form' %>
</div>

app/views/home/_new_blog_form.html.erb
<!-- Trigger the modal with a button -->

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
        <p>Some text in the modal.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<div class="modal fade" id="new-blog-modal" role="dialog" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Blog</h4>
      </div>
      <%= form_for :blog, url: blogs_path, html: { class: 'form-horizontal' } do %>
        <div class="modal-body">
          <div class="form-group">
            <label for="inputTitle" class="col-sm-2 control-label">Title</label>
            <div class="col-sm-10">
              <input type="text" name="title" class="form-control" id="inputTitle" placeholder="Title" required>
            </div>
          </div>
          <div class="form-group">
            <label for="inputPost" class="col-sm-2 control-label">Post</label>
            <div class="col-sm-10">
              <textarea class="form-control" name="body" id="inputPost" placeholder="Enter post" required></textarea>
            </div>
          </div>
           <div class="form-group">
            <label for="inputUsername" class="col-sm-2 control-label">Username</label>
            <div class="col-sm-10">
              <input type="text" name="username" class="form-control" id="inputUsername" placeholder="Username" required>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button id="submitNewPost" type="submit" class="btn btn-primary">Submit</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/about.html.erb
  <div class="intro">

	<h2>About Me</h2>
	<p>My name is Anukrity Jain and I am a software programmer. I specialise in a multi-disciplined approach to my work incorporating design and development. I have a vast experience of coding in C++.</p>
	<p>My quest for learning new technologies led me to developing and publishing the following mobile apps</p>
	<ul>
		<li><strong><a href="https://play.google.com/store/apps/details?id=com.ezeeideas.magicflood&hl=en" target="_blank">Magic Flood</a></strong></li>
		<li><strong><a href ="https://play.google.com/store/apps/details?id=com.ezeeideas.wordjam&hl=en" target="_blank">Word Jam</a></strong></li>
	</ul>
	 
	<p>Currently, learning Web Development and developing a social integration webapp that allows users to post challenges related to image filters and custom captions, and also provides an ecosystem where users can browse, search, comment and share their creations.</p> 
	<p>Based in Singapore, I studied at the University in India, where I gained a 1st Class Masters degree in Computer Application.</p>
	

	<iframe width="560" height="315" src="https://www.youtube.com/embed/z8GHf-aELjY?rel=0" frameborder="0" allowfullscreen></iframe>

  </div>

app/views/home/contact.html.erb
<div  class= "cnt">
	<div class="intro">
		<h2>Contact Me</h2>
		<p>You can drop me an <a href="mailto:anukrity.jain@gmail.com">email</a> or visit my <a href="https://github.com/AnukrityJain" target="_blank">Github page</a>.</p>
	</div>
</div>

app/views/home/index.html.erb
  <div class="intro">
  <p>This website is a result of a technical task which is a pre-requisite to be a part of "The TechLadies Bootcamp 3"</p>
  <p>I would love to be a part of this bootcamp, as it gives me an opportunity to learn something new and provides me a chance to make my career in the IT industry.</p>
  </div>


<div id="myCarousel" class="carousel slide " data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag('C1.JPG', alt: 'Bali') %>
    </div>

    <div class="item">
      <%= image_tag('C2.JPG', alt: 'Bali')  %>
    </div>

    <div class="item">
      <%= image_tag('C3.JPG', alt: 'Bali')  %>
    </div>
  </div>

  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechLadies Task</title>
   

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= javascript_include_tag    'application', 'data-turbolinks-track': 'true' %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
  	  <div class="container-fluid">
  	    <div class="navbar-header">
  	      <a class="navbar-brand" href="/">Anukrity's TechLadies Website</a>
  	    </div>
  	    <ul class="nav navbar-nav">
  	      <li><a href="/about">About Me</a></li>
  	      <li><a href="/blogs">Blog</a></li>
  	      <li><a href="/contact">Contact Me</a></li>
  	    </ul>
  	  </div>
  	</nav>
    <div class="belowNavbar">
    <%= yield %>
    </div>
  </body>
</html>